export interface Phrase {
  /** The canonical Spanish phrase, lowercased and accented correctly. */
  phrase: string;
  /** A short English meaning shown in the popover. */
  meaning: string;
}

/**
 * Hardcoded stock phrases / connectors / idioms worth flagging for a learner.
 * Matching is case- and accent-insensitive (see normalize / findPhrases), so
 * each entry is stored once in its canonical lowercase, accented form. Grows
 * over time. Discontinuous correlatives (ni... ni, tanto... como) live in
 * CORRELATIVE_PHRASES instead, since they need a different matcher.
 */
export const PHRASES: Phrase[] = [
  // --- Connectors / stock phrases ---
  { phrase: "a pesar de", meaning: "in spite of, despite" },
  { phrase: "a pesar de que", meaning: "despite the fact that" },
  { phrase: "a pesar de todo", meaning: "in spite of everything" },
  { phrase: "aunque", meaning: "although, even though" },
  { phrase: "sin embargo", meaning: "however, nevertheless" },
  { phrase: "no obstante", meaning: "nevertheless, notwithstanding" },
  { phrase: "hay que", meaning: "one must, it is necessary to" },
  { phrase: "tener que", meaning: "to have to" },
  { phrase: "por sí solo", meaning: "by itself, on its own" },
  { phrase: "por sí mismo", meaning: "by oneself, on one's own" },
  { phrase: "en vez de", meaning: "instead of" },
  { phrase: "en lugar de", meaning: "instead of" },
  { phrase: "por lo tanto", meaning: "therefore, so" },
  { phrase: "por tanto", meaning: "therefore" },
  { phrase: "por consiguiente", meaning: "consequently, therefore" },
  { phrase: "en consecuencia", meaning: "consequently, as a result" },
  { phrase: "por eso", meaning: "that's why, for that reason" },
  { phrase: "así que", meaning: "so, therefore" },
  { phrase: "de ahí que", meaning: "hence, that's why" },
  { phrase: "por lo que", meaning: "so, which is why" },
  { phrase: "en cuanto", meaning: "as soon as" },
  { phrase: "en cuanto a", meaning: "as for, regarding" },
  { phrase: "debido a", meaning: "due to, owing to" },
  { phrase: "a causa de", meaning: "because of" },
  { phrase: "por culpa de", meaning: "because of (blame)" },
  { phrase: "gracias a", meaning: "thanks to" },
  { phrase: "ya que", meaning: "since, given that" },
  { phrase: "puesto que", meaning: "since, given that" },
  { phrase: "dado que", meaning: "given that" },
  { phrase: "a raíz de", meaning: "as a result of, following" },
  { phrase: "en vista de", meaning: "in view of" },
  { phrase: "además", meaning: "moreover, furthermore" },
  { phrase: "además de", meaning: "in addition to, besides" },
  { phrase: "asimismo", meaning: "likewise, also" },
  { phrase: "aparte de", meaning: "apart from, aside from" },
  { phrase: "a menos que", meaning: "unless" },
  { phrase: "a no ser que", meaning: "unless" },
  { phrase: "salvo que", meaning: "except that, unless" },
  { phrase: "con tal de", meaning: "as long as, in order to" },
  { phrase: "con tal de que", meaning: "provided that, as long as" },
  { phrase: "siempre que", meaning: "as long as, whenever" },
  { phrase: "siempre y cuando", meaning: "as long as, provided that" },
  { phrase: "antes de", meaning: "before" },
  { phrase: "antes de que", meaning: "before" },
  { phrase: "después de", meaning: "after" },
  { phrase: "después de que", meaning: "after" },
  { phrase: "a fin de", meaning: "in order to" },
  { phrase: "a fin de que", meaning: "so that, in order that" },
  { phrase: "para que", meaning: "so that, in order that" },
  { phrase: "de modo que", meaning: "so that, in such a way that" },
  { phrase: "de manera que", meaning: "so that, in such a way that" },
  { phrase: "de forma que", meaning: "so that, in such a way that" },
  { phrase: "mientras que", meaning: "whereas, while" },
  { phrase: "mientras tanto", meaning: "meanwhile" },
  { phrase: "tan pronto como", meaning: "as soon as" },
  { phrase: "cada vez que", meaning: "every time, whenever" },
  { phrase: "una vez que", meaning: "once" },
  { phrase: "a medida que", meaning: "as, while" },
  { phrase: "hasta que", meaning: "until" },
  { phrase: "desde que", meaning: "since (time)" },
  { phrase: "por otro lado", meaning: "on the other hand" },
  { phrase: "por un lado", meaning: "on one hand" },
  { phrase: "en cambio", meaning: "on the other hand, instead" },
  { phrase: "al contrario", meaning: "on the contrary" },
  { phrase: "por el contrario", meaning: "on the contrary" },
  { phrase: "aun así", meaning: "even so, still" },
  { phrase: "aun cuando", meaning: "even when, even though" },
  { phrase: "pese a", meaning: "despite, in spite of" },
  { phrase: "pese a que", meaning: "despite the fact that" },
  { phrase: "si bien", meaning: "although, while" },
  { phrase: "por más que", meaning: "no matter how much" },
  { phrase: "de hecho", meaning: "in fact, actually" },
  { phrase: "en realidad", meaning: "actually, in reality" },
  { phrase: "en efecto", meaning: "indeed, in effect" },
  { phrase: "es decir", meaning: "that is to say, in other words" },
  { phrase: "o sea", meaning: "in other words, that is" },
  { phrase: "más bien", meaning: "rather, instead" },
  { phrase: "sobre todo", meaning: "above all, especially" },
  { phrase: "por ejemplo", meaning: "for example" },
  { phrase: "por cierto", meaning: "by the way" },
  { phrase: "a propósito", meaning: "by the way, on purpose" },
  { phrase: "de todos modos", meaning: "anyway, in any case" },
  { phrase: "de todas formas", meaning: "anyway, in any case" },
  { phrase: "de todas maneras", meaning: "anyway, in any case" },
  { phrase: "de cualquier modo", meaning: "in any case, anyway" },
  { phrase: "sea como sea", meaning: "one way or another" },
  { phrase: "en cualquier caso", meaning: "in any case" },
  { phrase: "en ese caso", meaning: "in that case" },
  { phrase: "de lo contrario", meaning: "otherwise" },
  { phrase: "por lo menos", meaning: "at least" },
  { phrase: "al menos", meaning: "at least" },
  { phrase: "por supuesto", meaning: "of course" },
  { phrase: "desde luego", meaning: "of course, certainly" },
  { phrase: "claro que", meaning: "of course (that)" },
  { phrase: "sin duda", meaning: "without a doubt" },
  { phrase: "por lo visto", meaning: "apparently, evidently" },
  { phrase: "al parecer", meaning: "apparently, seemingly" },
  { phrase: "a lo mejor", meaning: "maybe, perhaps" },
  { phrase: "tal vez", meaning: "maybe, perhaps" },
  { phrase: "quizás", meaning: "maybe, perhaps" },
  { phrase: "en resumen", meaning: "in summary, in short" },
  { phrase: "en conclusión", meaning: "in conclusion" },
  { phrase: "en fin", meaning: "in short, anyway" },
  { phrase: "por fin", meaning: "finally, at last" },
  { phrase: "al final", meaning: "in the end, finally" },
  { phrase: "en primer lugar", meaning: "firstly, in the first place" },
  { phrase: "en segundo lugar", meaning: "secondly" },
  { phrase: "por último", meaning: "lastly, finally" },
  { phrase: "ante todo", meaning: "first of all, above all" },
  { phrase: "para empezar", meaning: "to begin with" },
  { phrase: "a continuación", meaning: "next, following" },
  { phrase: "a la vez", meaning: "at the same time" },
  { phrase: "al mismo tiempo", meaning: "at the same time" },
  { phrase: "de repente", meaning: "suddenly" },
  { phrase: "de pronto", meaning: "suddenly" },
  { phrase: "de vez en cuando", meaning: "from time to time" },
  { phrase: "a menudo", meaning: "often" },
  { phrase: "a veces", meaning: "sometimes" },
  { phrase: "enseguida", meaning: "right away, immediately" },
  { phrase: "por ahora", meaning: "for now" },
  { phrase: "por el momento", meaning: "for the moment" },
  { phrase: "hoy en día", meaning: "nowadays" },
  { phrase: "a la larga", meaning: "in the long run" },
  { phrase: "a corto plazo", meaning: "in the short term" },
  { phrase: "a largo plazo", meaning: "in the long term" },
  { phrase: "en cierto modo", meaning: "in a way, in a sense" },
  { phrase: "en parte", meaning: "partly, in part" },
  { phrase: "por completo", meaning: "completely" },
  { phrase: "del todo", meaning: "entirely, completely" },
  { phrase: "en absoluto", meaning: "not at all" },
  { phrase: "ni siquiera", meaning: "not even" },
  { phrase: "según", meaning: "according to" },
  { phrase: "a través de", meaning: "through, by means of" },
  { phrase: "por medio de", meaning: "by means of" },
  { phrase: "a partir de", meaning: "starting from, as of" },
  { phrase: "a lo largo de", meaning: "throughout, along" },
  { phrase: "alrededor de", meaning: "around, approximately" },
  { phrase: "cerca de", meaning: "near, close to" },
  { phrase: "lejos de", meaning: "far from" },
  { phrase: "dentro de", meaning: "within, inside" },
  { phrase: "fuera de", meaning: "outside of, apart from" },
  { phrase: "junto a", meaning: "next to, alongside" },
  { phrase: "junto con", meaning: "together with" },
  { phrase: "en torno a", meaning: "around, concerning" },
  { phrase: "respecto a", meaning: "with respect to, regarding" },
  { phrase: "con respecto a", meaning: "with respect to, regarding" },
  { phrase: "en relación con", meaning: "in relation to" },
  { phrase: "en función de", meaning: "depending on, based on" },
  { phrase: "a base de", meaning: "based on, by means of" },
  { phrase: "en base a", meaning: "based on" },
  { phrase: "de acuerdo con", meaning: "in accordance with" },
  { phrase: "conforme a", meaning: "in accordance with" },
  { phrase: "en contra de", meaning: "against" },
  { phrase: "a favor de", meaning: "in favor of" },
  { phrase: "frente a", meaning: "facing, compared to" },
  { phrase: "encima de", meaning: "on top of, above" },
  { phrase: "debajo de", meaning: "underneath, below" },
  { phrase: "delante de", meaning: "in front of" },
  { phrase: "detrás de", meaning: "behind" },
  { phrase: "enfrente de", meaning: "across from, opposite" },
  { phrase: "al lado de", meaning: "next to, beside" },
  { phrase: "en medio de", meaning: "in the middle of" },
  { phrase: "sino que", meaning: "but rather" },
  // --- Idioms / fixed expressions ---
  { phrase: "darse cuenta de", meaning: "to realize" },
  { phrase: "tener ganas de", meaning: "to feel like, to want to" },
  { phrase: "echar de menos", meaning: "to miss (someone/something)" },
  { phrase: "valer la pena", meaning: "to be worth it" },
  { phrase: "tomar el pelo", meaning: "to tease, to pull someone's leg" },
  { phrase: "hacer falta", meaning: "to be necessary, to be lacking" },
  { phrase: "dar igual", meaning: "to not matter, to be all the same" },
  { phrase: "dar lo mismo", meaning: "to make no difference" },
  { phrase: "ponerse de acuerdo", meaning: "to come to an agreement" },
  { phrase: "llevar a cabo", meaning: "to carry out, to accomplish" },
  { phrase: "tener en cuenta", meaning: "to take into account, to keep in mind" },
  { phrase: "tomar en cuenta", meaning: "to take into account" },
  { phrase: "tener lugar", meaning: "to take place" },
  { phrase: "dar a conocer", meaning: "to make known, to announce" },
  { phrase: "darse prisa", meaning: "to hurry up" },
  { phrase: "tener prisa", meaning: "to be in a hurry" },
  { phrase: "hacer caso", meaning: "to pay attention, to heed" },
  { phrase: "hacer caso omiso", meaning: "to ignore, to disregard" },
  { phrase: "prestar atención", meaning: "to pay attention" },
  { phrase: "tener razón", meaning: "to be right" },
  { phrase: "no tener nada que ver", meaning: "to have nothing to do with" },
  { phrase: "tener que ver con", meaning: "to have to do with" },
  { phrase: "echar a perder", meaning: "to spoil, to ruin" },
  { phrase: "echar un vistazo", meaning: "to take a look, to glance" },
  { phrase: "echar una mano", meaning: "to lend a hand, to help" },
  { phrase: "echar la culpa", meaning: "to put the blame on" },
  { phrase: "echar en cara", meaning: "to throw in someone's face, to reproach" },
  { phrase: "echar chispas", meaning: "to be furious, to be fuming" },
  { phrase: "dar la vuelta", meaning: "to turn around, to flip" },
  { phrase: "dar un paseo", meaning: "to take a walk" },
  { phrase: "dar una vuelta", meaning: "to take a stroll, to go for a ride" },
  { phrase: "dar con", meaning: "to find, to come across" },
  { phrase: "dar por sentado", meaning: "to take for granted" },
  { phrase: "darse por vencido", meaning: "to give up" },
  { phrase: "dar en el clavo", meaning: "to hit the nail on the head" },
  { phrase: "dar gato por liebre", meaning: "to swindle, to deceive" },
  { phrase: "ponerse de pie", meaning: "to stand up" },
  { phrase: "ponerse en contacto", meaning: "to get in touch" },
  { phrase: "ponerse las pilas", meaning: "to get one's act together" },
  { phrase: "ponerse rojo", meaning: "to blush, to turn red" },
  { phrase: "ponerse al día", meaning: "to catch up, to get up to date" },
  { phrase: "ponerse las botas", meaning: "to stuff oneself, to make a killing" },
  { phrase: "poner en marcha", meaning: "to start up, to set in motion" },
  { phrase: "poner de manifiesto", meaning: "to make clear, to reveal" },
  { phrase: "poner en duda", meaning: "to call into question, to doubt" },
  { phrase: "poner el grito en el cielo", meaning: "to hit the roof, to be up in arms" },
  { phrase: "hacerse el tonto", meaning: "to play dumb" },
  { phrase: "hacerse cargo de", meaning: "to take charge of, to take responsibility for" },
  { phrase: "hacer cola", meaning: "to wait in line" },
  { phrase: "hacer las maletas", meaning: "to pack one's bags" },
  { phrase: "hacer daño", meaning: "to hurt, to harm" },
  { phrase: "hacer un esfuerzo", meaning: "to make an effort" },
  { phrase: "hacer la vista gorda", meaning: "to turn a blind eye" },
  { phrase: "hacer hincapié", meaning: "to emphasize, to stress" },
  { phrase: "tomar una decisión", meaning: "to make a decision" },
  { phrase: "tomar partido", meaning: "to take sides" },
  { phrase: "tomar cartas en el asunto", meaning: "to take action on a matter" },
  { phrase: "tomar el sol", meaning: "to sunbathe" },
  { phrase: "tener cuidado", meaning: "to be careful" },
  { phrase: "tener éxito", meaning: "to be successful" },
  { phrase: "tener miedo", meaning: "to be afraid" },
  { phrase: "tener sentido", meaning: "to make sense" },
  { phrase: "tener la culpa", meaning: "to be to blame" },
  { phrase: "tener buena pinta", meaning: "to look good (appealing)" },
  { phrase: "tener mala leche", meaning: "to be bad-tempered" },
  { phrase: "no tener pelos en la lengua", meaning: "to not mince words" },
  { phrase: "no tener ni idea", meaning: "to have no idea" },
  { phrase: "estar de acuerdo", meaning: "to agree" },
  { phrase: "estar a punto de", meaning: "to be about to" },
  { phrase: "estar harto de", meaning: "to be fed up with" },
  { phrase: "estar al tanto", meaning: "to be up to date, to be aware" },
  { phrase: "estar de moda", meaning: "to be in fashion" },
  { phrase: "estar a gusto", meaning: "to be comfortable, at ease" },
  { phrase: "estar hecho polvo", meaning: "to be exhausted, worn out" },
  { phrase: "estar en las nubes", meaning: "to have one's head in the clouds" },
  { phrase: "estar como una cabra", meaning: "to be crazy, to be nuts" },
  { phrase: "estar en su salsa", meaning: "to be in one's element" },
  { phrase: "estar entre la espada y la pared", meaning: "to be between a rock and a hard place" },
  { phrase: "estar para el arrastre", meaning: "to be worn out, done in" },
  { phrase: "estar de buen humor", meaning: "to be in a good mood" },
  { phrase: "estar de mal humor", meaning: "to be in a bad mood" },
  { phrase: "quedarse en blanco", meaning: "to go blank, to draw a blank" },
  { phrase: "quedarse de piedra", meaning: "to be stunned, dumbfounded" },
  { phrase: "quedarse con", meaning: "to keep, to hold on to" },
  { phrase: "quedar en", meaning: "to agree to, to arrange to" },
  { phrase: "ir de compras", meaning: "to go shopping" },
  { phrase: "ir al grano", meaning: "to get to the point" },
  { phrase: "ir tirando", meaning: "to get by, to manage" },
  { phrase: "ir de juerga", meaning: "to go out partying" },
  { phrase: "salir bien", meaning: "to turn out well" },
  { phrase: "salir mal", meaning: "to go wrong, to turn out badly" },
  { phrase: "salirse con la suya", meaning: "to get one's way" },
  { phrase: "salir adelante", meaning: "to get ahead, to pull through" },
  { phrase: "meter la pata", meaning: "to put one's foot in it, to mess up" },
  { phrase: "costar un ojo de la cara", meaning: "to cost an arm and a leg" },
  { phrase: "costar trabajo", meaning: "to be difficult, to be hard" },
  { phrase: "no pegar ojo", meaning: "to not sleep a wink" },
  { phrase: "ser pan comido", meaning: "to be a piece of cake, easy" },
  { phrase: "ser uña y carne", meaning: "to be inseparable, thick as thieves" },
  { phrase: "ser la gota que colma el vaso", meaning: "to be the last straw" },
  { phrase: "andarse por las ramas", meaning: "to beat around the bush" },
  { phrase: "buscar tres pies al gato", meaning: "to overcomplicate things" },
  { phrase: "tirar la toalla", meaning: "to throw in the towel, to give up" },
  { phrase: "matar dos pájaros de un tiro", meaning: "to kill two birds with one stone" },
  { phrase: "en un abrir y cerrar de ojos", meaning: "in the blink of an eye" },
  { phrase: "de tal palo tal astilla", meaning: "like father, like son" },
  { phrase: "más vale tarde que nunca", meaning: "better late than never" },
  { phrase: "más vale prevenir que curar", meaning: "better safe than sorry" },
  { phrase: "no hay mal que por bien no venga", meaning: "every cloud has a silver lining" },
  { phrase: "a caballo regalado no le mires el diente", meaning: "don't look a gift horse in the mouth" },
  { phrase: "llover a cántaros", meaning: "to rain cats and dogs" },
  { phrase: "pasarlo bien", meaning: "to have a good time" },
  { phrase: "pasarlo mal", meaning: "to have a hard time" },
  { phrase: "caer bien", meaning: "to be likable, to make a good impression" },
  { phrase: "caer mal", meaning: "to dislike, to make a bad impression" },
  { phrase: "caer en la cuenta", meaning: "to realize, to catch on" },
  { phrase: "sacar provecho", meaning: "to benefit, to take advantage" },
  { phrase: "sacar de quicio", meaning: "to drive crazy, to exasperate" },
  { phrase: "sacar adelante", meaning: "to bring forward, to support successfully" },
  { phrase: "llamar la atención", meaning: "to attract attention, to stand out" },
  { phrase: "perder el tiempo", meaning: "to waste time" },
  { phrase: "perder los estribos", meaning: "to lose one's temper" },
  { phrase: "perder de vista", meaning: "to lose sight of" },
  { phrase: "dejar en paz", meaning: "to leave alone" },
  { phrase: "dejar plantado", meaning: "to stand someone up" },
  { phrase: "dejar de", meaning: "to stop (doing something)" },
  { phrase: "acabar de", meaning: "to have just (done something)" },
  { phrase: "volver a", meaning: "to do again" },
  { phrase: "tratarse de", meaning: "to be about, to be a matter of" },
  { phrase: "ocuparse de", meaning: "to take care of, to deal with" },
  { phrase: "encargarse de", meaning: "to take charge of" },
  { phrase: "acordarse de", meaning: "to remember" },
  { phrase: "olvidarse de", meaning: "to forget" },
  { phrase: "quejarse de", meaning: "to complain about" },
  { phrase: "burlarse de", meaning: "to make fun of" },
  { phrase: "fijarse en", meaning: "to notice, to pay attention to" },
  { phrase: "contar con", meaning: "to count on, to rely on" },
  { phrase: "soñar con", meaning: "to dream about" },
  { phrase: "pensar en", meaning: "to think about" },
  { phrase: "tardar en", meaning: "to take time to, to be late in" },
  { phrase: "consistir en", meaning: "to consist of" },
  { phrase: "convertirse en", meaning: "to turn into, to become" },
  { phrase: "importar un bledo", meaning: "to not care at all" },
  { phrase: "no dar abasto", meaning: "to be unable to cope, to be overwhelmed" },
  { phrase: "darle vueltas a algo", meaning: "to mull something over" },
  { phrase: "estar al loro", meaning: "to be alert, to be in the know" },
  { phrase: "guardar cama", meaning: "to stay in bed (when sick)" },
  { phrase: "echar raíces", meaning: "to put down roots, to settle" },
  { phrase: "hacer buen tiempo", meaning: "to be nice weather" },
  // --- Conversational discourse markers ---
  { phrase: "a ver", meaning: "let's see / now then" },
  { phrase: "en plan", meaning: "like, sort of (filler)" },
  { phrase: "pues nada", meaning: "anyway, so that's that" },
  { phrase: "qué va", meaning: "no way, not at all" },
  { phrase: "ni hablar", meaning: "no way, out of the question" },
  { phrase: "por si acaso", meaning: "just in case" },
  { phrase: "menos mal", meaning: "thank goodness" },
  { phrase: "o sea que", meaning: "so, in other words" },
  { phrase: "es que", meaning: "it's just that" },
  { phrase: "pues eso", meaning: "so yeah, that's it" },
  { phrase: "total que", meaning: "long story short" },
  { phrase: "ya que estamos", meaning: "while we're at it" },
  { phrase: "a todo esto", meaning: "by the way, speaking of which" },
  { phrase: "dicho esto", meaning: "that said" },
  { phrase: "dicho sea de paso", meaning: "incidentally" },
  { phrase: "que conste", meaning: "let it be clear, mind you" },
  { phrase: "venga ya", meaning: "come on, no way" },
  { phrase: "anda ya", meaning: "come off it, no way" },
  { phrase: "qué dices", meaning: "what are you saying, no way" },
  { phrase: "resulta que", meaning: "it turns out that" },
  { phrase: "lo que pasa es que", meaning: "the thing is" },
  { phrase: "o algo así", meaning: "or something like that" },
  { phrase: "más o menos", meaning: "more or less, so-so" },
  { phrase: "que yo sepa", meaning: "as far as I know" },
  { phrase: "por lo que veo", meaning: "from what I see" },
  { phrase: "ahora que lo dices", meaning: "now that you mention it" },
  { phrase: "ahora que lo pienso", meaning: "now that I think about it" },
  { phrase: "la verdad es que", meaning: "the truth is" },
  { phrase: "para serte sincero", meaning: "to be honest with you" },
  { phrase: "entre nosotros", meaning: "between us, off the record" },
  { phrase: "como quien dice", meaning: "so to speak" },
  { phrase: "por así decirlo", meaning: "so to speak" },
  // --- Reactions ---
  { phrase: "me da igual", meaning: "I don't care, whatever" },
  { phrase: "no pasa nada", meaning: "no problem, it's fine" },
  { phrase: "ya está", meaning: "that's it, done" },
  { phrase: "qué más da", meaning: "what does it matter" },
  { phrase: "cómo no", meaning: "of course, sure" },
  { phrase: "ni modo", meaning: "oh well, nothing to be done" },
  { phrase: "ni de broma", meaning: "no way, not even joking" },
  { phrase: "ni loco", meaning: "no way, not a chance" },
  { phrase: "para nada", meaning: "not at all" },
  { phrase: "qué remedio", meaning: "what can you do, no choice" },
  { phrase: "así es la vida", meaning: "that's life" },
  { phrase: "qué le vamos a hacer", meaning: "what can you do" },
  { phrase: "ya veremos", meaning: "we'll see" },
  { phrase: "qué sé yo", meaning: "what do I know, who knows" },
  { phrase: "vete a saber", meaning: "who knows" },
  { phrase: "ya te digo", meaning: "tell me about it, for sure" },
  { phrase: "y que lo digas", meaning: "you can say that again" },
  { phrase: "ni más ni menos", meaning: "exactly, no more no less" },
  { phrase: "tal cual", meaning: "just like that, exactly" },
  { phrase: "eso es", meaning: "that's it, exactly" },
  { phrase: "claro que sí", meaning: "of course, absolutely" },
  { phrase: "claro que no", meaning: "of course not" },
  { phrase: "faltaría más", meaning: "of course, by all means" },
  { phrase: "cómo que no", meaning: "what do you mean no" },
  { phrase: "ya era hora", meaning: "about time" },
  { phrase: "qué fuerte", meaning: "how shocking, wow" },
  { phrase: "qué horror", meaning: "how awful" },
  { phrase: "qué pena", meaning: "what a shame" },
  { phrase: "qué lástima", meaning: "what a pity" },
  { phrase: "qué rollo", meaning: "what a drag, how boring" },
  { phrase: "qué rabia", meaning: "how annoying, how frustrating" },
  { phrase: "menudo lío", meaning: "what a mess" },
  { phrase: "vaya tela", meaning: "unbelievable, what a mess" },
  { phrase: "ya está bien", meaning: "that's enough" },
  { phrase: "ya basta", meaning: "enough already" },
  { phrase: "no me digas", meaning: "you don't say, really?" },
  { phrase: "no fastidies", meaning: "you're kidding, no way" },
  { phrase: "no me lo puedo creer", meaning: "I can't believe it" },
  { phrase: "te lo juro", meaning: "I swear" },
  { phrase: "lo que tú digas", meaning: "whatever you say" },
  { phrase: "como quieras", meaning: "as you like, whatever" },
  { phrase: "allá tú", meaning: "your call, suit yourself" },
  { phrase: "tú mismo", meaning: "suit yourself" },
  { phrase: "qué quieres que te diga", meaning: "what can I say" },
  { phrase: "no te preocupes", meaning: "don't worry" },
  // --- Conversational verb collocations ---
  { phrase: "tener sueño", meaning: "to be sleepy" },
  { phrase: "tener hambre", meaning: "to be hungry" },
  { phrase: "tener sed", meaning: "to be thirsty" },
  { phrase: "tener frío", meaning: "to be cold" },
  { phrase: "tener calor", meaning: "to be hot" },
  { phrase: "tener suerte", meaning: "to be lucky" },
  { phrase: "tener vergüenza", meaning: "to be ashamed, embarrassed" },
  { phrase: "tener celos", meaning: "to be jealous" },
  { phrase: "tener paciencia", meaning: "to be patient" },
  { phrase: "tener claro", meaning: "to be clear about, be sure" },
  { phrase: "tener pinta de", meaning: "to look like, seem" },
  { phrase: "tener fama de", meaning: "to have a reputation for" },
  { phrase: "tener mala cara", meaning: "to look unwell" },
  { phrase: "dar las gracias", meaning: "to thank" },
  { phrase: "pedir perdón", meaning: "to apologize" },
  { phrase: "pedir disculpas", meaning: "to apologize" },
  { phrase: "pasar de algo", meaning: "to not care about, blow off" },
  { phrase: "pasar de largo", meaning: "to walk right past, ignore" },
  { phrase: "dar pena", meaning: "to make sad, feel sorry for" },
  { phrase: "dar miedo", meaning: "to be scary, frighten" },
  { phrase: "dar asco", meaning: "to be disgusting" },
  { phrase: "dar rabia", meaning: "to make angry, annoy" },
  { phrase: "dar vergüenza", meaning: "to be embarrassing" },
  { phrase: "dar gusto", meaning: "to be a pleasure" },
  { phrase: "dar la mano", meaning: "to shake hands" },
  { phrase: "dar un beso", meaning: "to give a kiss" },
  { phrase: "dar un abrazo", meaning: "to give a hug" },
  { phrase: "dar la razón", meaning: "to agree, say someone's right" },
  { phrase: "dar marcha atrás", meaning: "to back out, reverse" },
  { phrase: "dar pie a", meaning: "to give rise to" },
  { phrase: "dar el visto bueno", meaning: "to give the go-ahead" },
  { phrase: "hacer una pregunta", meaning: "to ask a question" },
  { phrase: "hacer ejercicio", meaning: "to exercise" },
  { phrase: "hacer deporte", meaning: "to play sports" },
  { phrase: "hacer la compra", meaning: "to do the shopping" },
  { phrase: "hacer la cama", meaning: "to make the bed" },
  { phrase: "hacer ruido", meaning: "to make noise" },
  { phrase: "hacer planes", meaning: "to make plans" },
  { phrase: "hacer gracia", meaning: "to be funny, amuse" },
  { phrase: "hacer ilusión", meaning: "to be excited about, look forward to" },
  { phrase: "hacer de las suyas", meaning: "to be up to one's tricks" },
  { phrase: "tomar nota", meaning: "to take note" },
  { phrase: "tomar en serio", meaning: "to take seriously" },
  { phrase: "tomar prestado", meaning: "to borrow" },
  { phrase: "echar un trago", meaning: "to have a drink" },
  { phrase: "echar una siesta", meaning: "to take a nap" },
  { phrase: "echar una ojeada", meaning: "to take a quick look" },
  { phrase: "poner la mesa", meaning: "to set the table" },
  { phrase: "poner un ejemplo", meaning: "to give an example" },
  { phrase: "poner nervioso", meaning: "to make nervous" },
  { phrase: "ponerse enfermo", meaning: "to get sick" },
  { phrase: "ponerse triste", meaning: "to get sad" },
  { phrase: "ponerse contento", meaning: "to get happy" },
  { phrase: "ponerse nervioso", meaning: "to get nervous" },
  { phrase: "quedarse callado", meaning: "to keep quiet" },
  { phrase: "quedarse dormido", meaning: "to fall asleep" },
  { phrase: "quedarse corto", meaning: "to fall short, understate" },
  { phrase: "quedar bien", meaning: "to make a good impression" },
  { phrase: "quedar mal", meaning: "to make a bad impression" },
  { phrase: "caer gordo", meaning: "to dislike someone, rub the wrong way" },
  { phrase: "llevarse bien", meaning: "to get along well" },
  { phrase: "llevarse mal", meaning: "to not get along" },
  { phrase: "darse la vuelta", meaning: "to turn around" },
  { phrase: "irse de vacaciones", meaning: "to go on vacation" },
  { phrase: "salir a cenar", meaning: "to go out to dinner" },
  // --- Conversational idioms ---
  { phrase: "dar la lata", meaning: "to be a nuisance, pester" },
  { phrase: "estar frito", meaning: "to be done for, fast asleep" },
  { phrase: "ponerse morado", meaning: "to stuff oneself, pig out" },
  { phrase: "estar como pez en el agua", meaning: "to be in one's element" },
  { phrase: "estar de los nervios", meaning: "to be a nervous wreck" },
  { phrase: "estar hasta las narices", meaning: "to be fed up" },
  { phrase: "estar hasta el gorro", meaning: "to be fed up" },
  { phrase: "estar hasta la coronilla", meaning: "to be sick and tired" },
  { phrase: "estar sin blanca", meaning: "to be broke" },
  { phrase: "estar forrado", meaning: "to be loaded, rich" },
  { phrase: "estar en la luna", meaning: "to be daydreaming" },
  { phrase: "estar de morros", meaning: "to be sulking" },
  { phrase: "ser un rollo", meaning: "to be a bore, a drag" },
  { phrase: "ser un chollo", meaning: "to be a bargain, a steal" },
  { phrase: "ser una pasada", meaning: "to be amazing, over the top" },
  { phrase: "costar una fortuna", meaning: "to cost a fortune" },
  { phrase: "hacer la pelota", meaning: "to suck up, brown-nose" },
  { phrase: "irse de la lengua", meaning: "to let slip, blab" },
  { phrase: "meter las narices", meaning: "to stick one's nose in" },
  { phrase: "meterse en líos", meaning: "to get into trouble" },
  { phrase: "armar un lío", meaning: "to make a fuss, cause chaos" },
  { phrase: "montar un pollo", meaning: "to make a scene" },
  { phrase: "dar plantón", meaning: "to stand someone up" },
  { phrase: "poner verde a alguien", meaning: "to badmouth someone" },
  { phrase: "tirar la casa por la ventana", meaning: "to spare no expense" },
  { phrase: "pagar el pato", meaning: "to take the blame" },
  { phrase: "buscarse la vida", meaning: "to fend for oneself" },
  { phrase: "hacerse el sueco", meaning: "to play dumb, ignore" },
  { phrase: "importar un pimiento", meaning: "to not care at all" },
  { phrase: "estar en el ajo", meaning: "to be in on it" },
  { phrase: "salir el tiro por la culata", meaning: "to backfire" },
  { phrase: "ahogarse en un vaso de agua", meaning: "to make a mountain out of a molehill" },
  { phrase: "echar leña al fuego", meaning: "to add fuel to the fire" },
  // --- Spain colloquial ---
  { phrase: "flipar en colores", meaning: "to be totally blown away" },
  { phrase: "ni de coña", meaning: "no way, not a chance" },
  { phrase: "qué morro", meaning: "what nerve, cheek" },
  { phrase: "tener morro", meaning: "to have nerve, be cheeky" },
  { phrase: "ser la leche", meaning: "to be amazing, unbelievable" },
  { phrase: "pasarlo pipa", meaning: "to have a great time" },
  { phrase: "qué guay", meaning: "how cool, awesome" },
  { phrase: "ser un crack", meaning: "to be a star, be great at it" },
  { phrase: "echar un cable", meaning: "to lend a hand" },
  { phrase: "ir de marcha", meaning: "to go out partying" },
  { phrase: "salir de fiesta", meaning: "to go out partying" },
  { phrase: "hacer botellón", meaning: "to drink outdoors in a group" },
  { phrase: "qué movida", meaning: "what a mess, what a hassle" },
  // --- Latin American colloquial ---
  { phrase: "órale", meaning: "wow, okay, let's go (Mex.)" },
  { phrase: "chévere", meaning: "cool, great" },
  { phrase: "al toque", meaning: "right away, instantly" },
  { phrase: "qué onda", meaning: "what's up, how's it going" },
  { phrase: "no manches", meaning: "no way, you're kidding (Mex.)" },
  { phrase: "la neta", meaning: "honestly, for real (Mex.)" },
  { phrase: "qué pedo", meaning: "what's up, what's the deal (Mex.)" },
  { phrase: "a poco", meaning: "really?, you don't say (Mex.)" },
  { phrase: "sale y vale", meaning: "deal, okay then (Mex.)" },
  { phrase: "qué hueva", meaning: "what a drag, so lazy (Mex.)" },
  { phrase: "echarse un taco", meaning: "to grab a bite (Mex.)" },
  { phrase: "buena onda", meaning: "good vibes, nice person" },
  { phrase: "mala onda", meaning: "bad vibes, not cool" },
  { phrase: "qué buena onda", meaning: "how cool, how nice" },
  { phrase: "estar pelado", meaning: "to be broke" },
  { phrase: "qué chimba", meaning: "how cool (Col. slang)" },
  { phrase: "pura vida", meaning: "all good, great (C.R.)" },
  { phrase: "qué quilombo", meaning: "what a mess (Arg.)" },
  { phrase: "al tiro", meaning: "right away (Chile)" },
  { phrase: "de una", meaning: "right away, for sure" },
  { phrase: "ni a palos", meaning: "no way, not a chance" },
  { phrase: "qué padre", meaning: "how cool, great (Mex.)" },
  { phrase: "qué chido", meaning: "how cool (Mex.)" },
];

/**
 * Discontinuous correlative connectors (two parts with words in between, e.g.
 * "ni café ni té"). NOT yet matched — a literal search can't find them. Stored
 * here for a future two-part matcher. Shape TBD; keep as raw patterns for now.
 */
export const CORRELATIVE_PHRASES: Phrase[] = [
  { phrase: "tanto... como", meaning: "both... and, as much... as" },
  { phrase: "ni... ni", meaning: "neither... nor" },
  { phrase: "o... o", meaning: "either... or" },
  { phrase: "no solo... sino también", meaning: "not only... but also" },
  { phrase: "ya sea... o", meaning: "whether... or" },
];

/** A located phrase within a piece of text. */
export interface PhraseSpan extends Phrase {
  /** Character offset of the match within the text (inclusive). */
  start: number;
  /** Character offset just past the match within the text. */
  end: number;
  /** The phrase exactly as it appears in the text (original case/accents). */
  text: string;
}

/** Lowercase and strip diacritics so matching ignores case and accents. */
function normalize(value: string): string {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "");
}

/**
 * Find every stock phrase in `text`, case- and accent-insensitively. May return
 * overlapping matches in arbitrary order — the caller resolves overlaps (see
 * dropOverlaps in runRules). NFD normalization preserves 1:1 character offsets
 * for Spanish text, so offsets map back onto the original string.
 */
export function findPhrases(text: string): PhraseSpan[] {
  const haystack = normalize(text);
  const found: PhraseSpan[] = [];

  for (const entry of PHRASES) {
    const needle = normalize(entry.phrase);
    let at = haystack.indexOf(needle);

    while (at !== -1) {
      found.push({
        ...entry,
        start: at,
        end: at + needle.length,
        text: text.slice(at, at + needle.length),
      });
      at = haystack.indexOf(needle, at + needle.length);
    }
  }

  return found;
}
